# Site settings
title: "Sambhav Jain | Delhi"
description: "Sambhav Jain | Delhi"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sambhav Jain"
resume_title:                   "Student Developer"
resume_contact_email:           "sambhavjain2612@gmail.com"
resume_contact_telephone:       "+91-858-806-2059"
resume_contact_address:         "New Delhi, India"
resume_header_contact_info: "New Delhi, India | +91-858-806-2059 | sambhavjain2612@gmail.com"
resume_header_intro: "<p>Charting the knowledge of the Internet, just like Galileo charted the stars.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/sambhav2612"
  resume_twitter_url:           "http://twitter.com/sambhavvjain"
  resume_facebook_url:          "https://facebook.com/sabhav2612"
  resume_linkedin_url:          "https://www.linkedin.com/in/sambhav-jain-88b62b62/"
  resume_website_url:           "httsp://sambhav2612.github.io"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
